### ISSUE TITLE
자동 포매팅 중단 기능 추가

### ISSUE THREAD

**Issue by ucyang** [CAU-OSS-2019/team-project-team14#19]
레이아웃이 제대로 출력되지 않는 등, 사용자가 프로그램 동작에 이상을 느꼈을 때 자동 포매팅을 수동으로 중단할 수 있는 기능이 제공되어야 합니다.

팝업 창에 중단/재개 버튼을 두고 관련 코드를 추가하면 간단히 해결될 것으로 보입니다.

**Comment by njw1204** [comment]
자동 포맷팅 만들 때 중단할 수 있는 함수 만들어주시면 좋겠습니다

+) 가능하다면 수동으로 영역 선택(드래그 등)해서 포맷팅 하는게 있어도 좋겠습니다

**Comment by njw1204** [comment]
#31 #35
