### ISSUE TITLE
웹 폰트를 내장합시다

### ISSUE THREAD

**Issue by ucyang** [CAU-OSS-2019/team-project-team14#55]
코드 인식 함수에서 사용되는 구글 웹 폰트가 현재 외부 CDN을 거치는 것으로 보입니다.

이는 성능 저하를 유발할 뿐만 아니라 불필요하게 외부에 의존하게 되므로
프로그램이 직접 포함하는 편이 좋을 것 같습니다.

따라서 해당 처리 및 PR을 요청합니다.

**Comment by njw1204** [comment]
#58

해결완료
