### ISSUE TITLE
Incorrect code detection

### ISSUE THREAD

**Issue by ihooni** [CAU-OSS-2019/team-project-team14#59]
**Execution env**

- Codify 1.0
- Chrome 74.0.3729.169

**Screenshot**

- 1st

![스크린샷 2019-05-28 오전 12 03 16](https://user-images.githubusercontent.com/37792049/58427935-04035b00-80dc-11e9-9e5f-9d0d092e8598.png)

- 2nd

![스크린샷 2019-05-28 오전 12 24 30](https://user-images.githubusercontent.com/37792049/58428911-ff8c7180-80de-11e9-93d4-a526fe0131c3.png)

- Editor screenshot of 1st screenshot error

![스크린샷 2019-05-28 오전 12 32 27](https://user-images.githubusercontent.com/37792049/58429239-3a42d980-80e0-11e9-9b02-e557249e41e9.png)

**url**
- https://stackoverflow.com/questions/605845/do-i-cast-the-result-of-malloc

##  

In this case, the beginning of the code is well detected, but the end of the code is strange.

**Comment by ucyang** [comment]
문제 확인했습니다.

최대한 이른 시일 내에 해결하겠습니다.

**Comment by ucyang** [comment]
#64

현재 develop 브랜치에서 문제 해결되었습니다.

차후 master 브랜치에 반영될 예정입니다.
