### ISSUE TITLE
Editor 코드 수정 후 팝업을 닫을 시  수정 내역이 저장되지 않습니다.

### ISSUE THREAD

**Issue by SeongYunKim** [CAU-OSS-2019/team-project-team14#60]
Editor 메뉴에서 코드창의 내용을 수정 한 후 팝업을 닫았다 열면 수정 내역이 저장되어 있지 않습니다.

내용이 수정될때 마다(또는 팝업이 닫힐 때) 코드 저장이 필요합니다.

**Comment by njw1204** [comment]
크롬 스토리지에는 분당 120회까지 저장이 가능한 제약 사항이 있습니다.
따라서 현재는 컴파일 시에만 코드 내용이 저장되도록 구현했습니다.
수정될때 마다 저장하는 것은 제약 사항으로 인해 힘들고, 팝업이 닫힐 때 코드를 저장하는 쪽으로 구현해주시면 감사하겠습니다.

**Comment by njw1204** [comment]
#62 완료
