### ISSUE TITLE
기존 웹사이트의 신택스를 덮어쓰면서 잘못된 신택싱을 합니다.

### ISSUE THREAD

**Issue by jhaemin** [CAU-OSS-2019/team-project-team14#66]
https://stackoverflow.com/questions/8547778/why-are-elementwise-additions-much-faster-in-separate-loops-than-in-a-combined-l

Codify 없이 페이지를 방문한 경우 기존 웹사이트가 신택스 처리를 잘 하고 있습니다.

![Screen Shot 2019-06-02 at 2 43 18 AM](https://user-images.githubusercontent.com/19797697/58751891-3f3cca00-84e0-11e9-9d55-1775191c181d.png)

Codify를 활성하하면 기존 신택스를 덮어쓰지만 잘못된 처리를 하고 있으며 중괄호 한 쌍이 끝나는 부분에서 끝이 납니다.

![Screen Shot 2019-06-02 at 2 43 23 AM](https://user-images.githubusercontent.com/19797697/58751906-77dca380-84e0-11e9-8ecf-9a38594afb60.png)

**Comment by ucyang** [comment]
#59 

기존 이슈와 유사한 문제로 보이며 현재 해결되었습니다.

또한, 중괄호 쌍의 인식과 관련한 알고리즘 개선은 현재 진행 중입니다.
