### ISSUE TITLE
Color highlighting needs to be intelligent

### ISSUE THREAD

**Issue by ihooni** [CAU-OSS-2019/team-project-team14#68]
**Execution env**

- Codify 1.0
- Chrome 74.0.3729.169

**Screenshot**

- highlighted by codify

<img width="355" alt="스크린샷 2019-06-02 오전 2 59 25" src="https://user-images.githubusercontent.com/37792049/58752065-6943bb80-84e3-11e9-8a69-ca6342e215ec.png">

##  

I think codify will be more useful if the program consider the background color when highlighting the code.

**Comment by ucyang** [comment]
문제 확인하였으나 더 알기 쉽게 해당 문제가 발생하는 웹 페이지의 URL을 남겨주시면 감사하겠습니다.

현재 구문 강조 스타일을 선택할 수 있는 기능과 더불어

팝업창 테마 선택 기능의 추가를 검토 중입니다.

**Comment by ihooni** [comment]
I'm sorry to miss it.

**url**
https://kin.naver.com/qna/detail.nhn?d1id=1&dirId=1040101&docId=327662132&qb=dm9pZCBkcmF3TWVudQ==&enc=utf8&section=kin&rank=1&search_sort=0&spq=0&pid=UnQ26lp0JywssLu25O8ssssssWC-435693&sid=AN0HexHs5AOMbYjm%2BDCaMQ%3D%3D
