### ISSUE TITLE
Django Secret Key 노출 문제

### ISSUE THREAD

**Issue by shieldnet** [CAU-OSS-2019/team-project-team14#70]
Django Secret Key가 server의 setting 파일에 그대로 노출되어 있습니다.
.py파일이니만큼 json이나 기타 파일로 따로 저장하시는걸 추천합니다.

**Comment by njw1204** [comment]
먼저 프로젝트에 관심 가져주셔서 감사합니다! 해당 부분은 저도 수정이 필요하다고 생각합니다. 혹시 수정하실 수 있으시다면 PR을 등록해주셔도 됩니다.

**Comment by shieldnet** [comment]
넵 조금 있다가 PR을 등록하겠습니다. 감사합니다

2019년 6월 14일 (금) 오후 6:44, Jongwoo Na <notifications@github.com>님이 작성:

**Comment by shieldnet** [comment]
@njw1204 Pull-Request를 등록하였습니다. Reviewer가 필요하다고 하니 한번 검토해주시면 감사하겠습니다.
