### ISSUE TITLE
api-server를 pip로 설치할 때 에러가 발생합니다.

### ISSUE THREAD

**Issue by Reichidad** [CAU-OSS-2019/team-project-team14#76]
![image](https://user-images.githubusercontent.com/47580804/59908301-12793400-9448-11e9-8e14-6c0e9e66a074.png)
api-server폴더의 readme에서의 서버 설치방법에 따라 진행하였습니다. 이 때, DB 스키마를 생성하는 과정에서 pip3가 아닌 pip로 생성하는 경우, django를 import할 수 없는 에러가 있습니다.

**Comment by njw1204** [comment]
해당 오류는 python3에 django가 설치되어있지 않아서 발생하는 문제로 보여집니다. 제 생각에는 사용하시는 컴퓨터에서 pip은 python2, pip3은 python3을 담당하고 있는 것 같습니다. 보통 파이썬 2와 3 버전이 모두 깔려있는 경우 이런 식으로 되어있는 경우가 많습니다. 해당 문제는 저희 프로젝트의 문제라기보다는 파이썬 환경 설정의 문제입니다. 저희가 도와드리기는 어려울 것 같습니다. 만약 제가 말한 것처럼 환경 설정이 되어 있다면 pip으로 설치했을때는 오류가 나는게 당연합니다. pip으로 설치하면 python2 쪽에 설치가 될 것이기 때문입니다.

**Comment by njw1204** [comment]
관련 사항을 README에 추가하도록 하겠습니다.
